# Generated by Django 5.2.17 on 2026-09-12 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Identificación (Cédula/Pasaporte)')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, default='', verbose_name='Dirección Habitual')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGanancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Porcentaje de Ganancia (%)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Configuración de Ganancia',
                'verbose_name_plural': 'Configuraciones de Ganancia',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPagoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Porcentaje Pago Inicial (%)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Configuración Pago Inicial',
                'verbose_name_plural': 'Configuraciones Pago Inicial',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('requiere_cantidad_manual', models.BooleanField(default=False, verbose_name='¿Requiere cantidad manual?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Evento')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del Evento')),
                ('cantidad_personas', models.PositiveIntegerField(verbose_name='Cantidad de Personas / Invitados')),
                ('direccion_evento', models.TextField(blank=True, default='', verbose_name='Dirección Exacta del Evento')),
                ('estado', models.CharField(choices=[('Solicitud', 'Solicitud Pendiente'), ('Cotizacion', 'Cotización Formal'), ('Evento', 'Evento Contratado'), ('Cancelada', 'Cancelada')], db_index=True, default='Solicitud', max_length=20, verbose_name='Estado')),
                ('modalidad_servicio', models.CharField(choices=[('Saloneros', 'Servicio a la mesa con Saloneros'), ('Bufete', 'Tipo bufete (Autoservicio)'), ('NoAplica', 'No Aplica')], default='Bufete', max_length=20, verbose_name='Modalidad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('notas_adicionales', models.TextField(blank=True, default='', verbose_name='Notas Adicionales')),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Subtotal Servicios (CRC)')),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Gastos Directos (CRC)')),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='% Ganancia')),
                ('monto_ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Monto Ganancia (CRC)')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=13.0, max_digits=5, verbose_name='% IVA')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Monto IVA (CRC)')),
                ('total_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total General (CRC)')),
                ('total_por_persona', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total por Persona (CRC)')),
                ('porcentaje_pago_inicial', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Pago Inicial')),
                ('monto_pago_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Monto Pago Inicial / Adelanto (CRC)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='core.cliente')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='core.tipoevento')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField(error_messages={'unique': 'Ya existe un evento contratado para esta fecha. Eventos68 solo atiende un evento exclusivo por día.'}, unique=True, verbose_name='Fecha del Evento')),
                ('cantidad_personas', models.PositiveIntegerField(verbose_name='Cantidad de Personas')),
                ('estado', models.CharField(choices=[('Contratado', 'Contratado'), ('EnProceso', 'En Preparación'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Contratado', max_length=20, verbose_name='Estado')),
                ('fecha_contratacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Contratación')),
                ('notas_operativas', models.TextField(blank=True, default='', verbose_name='Notas de Logística / Montaje')),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='core.cotizacion')),
            ],
            options={
                'verbose_name': 'Evento Contratado',
                'verbose_name_plural': 'Eventos Contratados',
                'ordering': ['fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción del Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del Gasto (CRC)')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes_gastos/', verbose_name='Comprobante de Gasto')),
                ('fecha_gasto', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='core.cotizacion')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='core.evento')),
            ],
            options={
                'verbose_name': 'Gasto Directo',
                'verbose_name_plural': 'Gastos Directos',
                'ordering': ['-fecha_gasto'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='Abono a presupuesto de evento', max_length=250, verbose_name='Descripción / Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Abonado (CRC)')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/', verbose_name='Comprobante de Transferencia / Recibo')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.evento')),
            ],
            options={
                'verbose_name': 'Abono / Pago',
                'verbose_name_plural': 'Abonos y Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_detalle', models.CharField(max_length=150, verbose_name='Nombre del Componente')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Unitario (CRC)')),
                ('unidad_medida', models.CharField(default='Por persona', max_length=50, verbose_name='Unidad de Medida')),
                ('categoria', models.CharField(blank=True, choices=[('Guarnicion', 'Guarnición'), ('Proteina', 'Proteína'), ('Ensalada', 'Ensalada'), ('Postre', 'Postre'), ('Bebida', 'Bebida'), ('Salsa', 'Salsa'), ('Mesa', 'Mesa'), ('Silla', 'Silla'), ('Mantel', 'Mantel'), ('Vajilla', 'Vajilla'), ('Cristaleria', 'Cristalería'), ('Transporte', 'Transporte'), ('Otro', 'Otro Componente')], max_length=50, null=True, verbose_name='Categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.servicio')),
            ],
            options={
                'verbose_name': 'Componente de Servicio',
                'verbose_name_plural': 'Componentes de Servicios',
                'ordering': ['servicio', 'categoria', 'nombre_detalle'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personalizado', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre Personalizado')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Unitario (CRC)')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Subtotal (CRC)')),
                ('requiere_saloneros', models.BooleanField(blank=True, null=True, verbose_name='¿Requiere Saloneros?')),
                ('es_bufete', models.BooleanField(blank=True, null=True, verbose_name='¿Es Bufete?')),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='imagenes_referencia/', verbose_name='Imagen de Referencia (Decoración)')),
                ('detalle_personalizado', models.TextField(blank=True, null=True, verbose_name='Detalle Personalizado / Notas')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.cotizacion')),
                ('detalle_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_cotizacion', to='core.detalleservicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='core.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
                'ordering': ['servicio', 'detalle_servicio'],
            },
        ),
    ]
