# Generated by Django 5.2.17 on 2026-09-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Guarnicion', 'Guarnición'), ('Proteina', 'Proteína'), ('Ensalada', 'Ensalada'), ('Postre', 'Postre'), ('Bebida', 'Bebida'), ('Salsa', 'Salsa'), ('Barra_Fuerte', 'Barra Fuerte / Típica'), ('Fast_Food', 'Carrito Fast Food'), ('Snack', 'Carrito de Snacks & Dulces'), ('Saludable', 'Estación Saludable'), ('Mesa', 'Mesa'), ('Silla', 'Silla'), ('Mantel', 'Mantel'), ('Vajilla', 'Vajilla'), ('Cristaleria', 'Cristalería'), ('Transporte', 'Transporte'), ('Otro', 'Otro Componente')], max_length=50, null=True, verbose_name='Categoría'),
        ),
    ]
