# Generated by Django 5.2.17 on 2026-09-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detalleservicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='alergias_restricciones',
            field=models.TextField(blank=True, default='No presenta / No aplica', verbose_name='Alergias o Restricciones Alimentarias'),
        ),
    ]
