# Generated by Django 5.2.17 on 2026-09-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cotizacion_alergias_restricciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='detalles_preparacion',
            field=models.TextField(blank=True, default='', verbose_name='Preferencias de Preparación, Salsas y Guarniciones'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='punto_salida',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Punto o Dirección de Salida / Origen'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Guarnicion', 'Guarnición'), ('Proteina', 'Proteína'), ('Ensalada', 'Ensalada'), ('Postre', 'Postre'), ('Bebida', 'Bebida'), ('Salsa', 'Salsa'), ('Barra_Fuerte', 'Barra Fuerte / Típica'), ('Fast_Food', 'Carrito Fast Food'), ('Snack', 'Carrito de Snacks & Dulces'), ('Saludable', 'Estación Saludable'), ('Manualidades', 'Estación de Manualidades & Creatividad'), ('Mesa', 'Mesa'), ('Silla', 'Silla'), ('Mantel', 'Mantel'), ('Vajilla', 'Vajilla'), ('Cristaleria', 'Cristalería'), ('Transporte', 'Transporte'), ('Otro', 'Otro Componente')], max_length=50, null=True, verbose_name='Categoría'),
        ),
    ]
